// <auto-generated />
using System;
using HomesEngland.Gateway.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HomesEngland.Gateway.Migrations
{
    [DbContext(typeof(AssetRegisterContext))]
    [Migration("20181116175602_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HomesEngland.Gateway.DapperAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountingYear");

                    b.Property<string>("Address");

                    b.Property<decimal?>("AgencyEquityLoan");

                    b.Property<DateTime?>("CompletionDateForHpiStart");

                    b.Property<decimal?>("Deposit");

                    b.Property<decimal?>("DeveloperEquityLoan");

                    b.Property<string>("DevelopingRslName");

                    b.Property<int?>("DifferenceFromImsExpectedCompletionToHopCompletionDate");

                    b.Property<DateTime?>("HopCompletionDate");

                    b.Property<DateTime?>("ImsActualCompletionDate");

                    b.Property<DateTime?>("ImsExpectedCompletionDate");

                    b.Property<DateTime?>("ImsLegalCompletionDate");

                    b.Property<string>("ImsOldRegion");

                    b.Property<string>("LocationLaRegionName");

                    b.Property<DateTime>("ModifiedDateTime");

                    b.Property<string>("MonthPaid");

                    b.Property<string>("NoOfBeds");

                    b.Property<string>("SchemeId");

                    b.Property<decimal?>("ShareOfRestrictedEquity");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
